env:
  browser: true
  es6: true
  jest: true
  jquery: true
globals:
  IMPORT_JQUERY: true
  FILTERIZR_ENV: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
  no-extra-semi:
    - error
